---
title: "3. Поиск сайтов протеолиза белков протеосомой по данным IEDB"
author: "Антон Смирнов"
date: "24.01.2023"
link-citations: true
output: html_document
bibliography: references_look_iedb_cleavage.bib
---

# Введение

The Immune Epitope Database (IEDB)@vita2019 - крупнейшая база данных по Т и В-клеточным эпитопам. Необходимо оценить частоту встречаемости аминокислот на С-конце эпитопа, так как с него как правило не идет процессинг антигена для МНС 1 класса.

Установить соединение с БД, развернутой на локальном сервере.

```{r}
con = RMySQL::dbConnect(RMySQL::MySQL(),
                            dbname='iedb',
                            host='localhost',
                            port=3306,
                            user='stotoshka',
                            password='meowmeow')
```

Типы экспериментов в БД.

```{sql connection=con}
SELECT category, count(category) FROM assay_type GROUP BY category;
```

Нам не нужны эксперименты с MHC и Naturally Processed, так как в них, как правило работают с линейными эпитопами и названия экспериментов соответствуют необходимым нам.

```{sql connection=con}
SELECT category, assay_type  FROM assay_type at2 WHERE category = 'MHC' ;
```

```{sql connection=con}
SELECT category, assay_type  FROM assay_type at2 WHERE category = 'Naturally Processed' ;
```

Необходимая нам информация содержится в таблицах mhc_elution и mhc_bind и связанных с ними.

```{sql connection=con}
SELECT DISTINCT at2.category,at2.assay_type FROM mhc_elution me 
INNER JOIN assay_type at2 ON as_type_id  = at2.assay_type_id;
```

```{sql connection=con}
SELECT DISTINCT at2.category,at2.assay_type FROM mhc_bind mb
INNER JOIN assay_type at2 ON as_type_id  = at2.assay_type_id 
```

# mhc_bind

Распределение по результатам

```{sql connection=con}
SELECT as_char_value, COUNT(as_char_value)  FROM mhc_bind GROUP BY as_char_value;
```

Всего строк в таблице

```{sql connection=con}
SELECT COUNT(*) FROM mhc_bind;
```

Отфильтруем строки с пустыми полями

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW filtered_bind
AS (SELECT mhc_bind_id, reference_id, curated_epitope_id, as_char_value, mhc_allele_restriction_id 
    FROM mhc_bind
    WHERE mhc_bind_id IS NOT NULL AND
          reference_id IS NOT NULL AND
          curated_epitope_id IS NOT NULL AND
          as_char_value IS NOT NULL AND
          mhc_allele_restriction_id IS NOT NULL);
```

Количество строк

```{sql connection=con}
SELECT COUNT(*) FROM filtered_bind;
```

# mhc_elution

Распределение по результатам

```{sql connection=con}
SELECT as_char_value, COUNT(as_char_value)  FROM mhc_elution GROUP BY as_char_value;
```

Всего строк в таблице

```{sql connection=con}
SELECT COUNT(*) FROM mhc_elution;
```

Отфильтруем строки с пустыми полями

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW filtered_elution
AS (SELECT mhc_elution_id, reference_id, curated_epitope_id, as_char_value, mhc_allele_restriction_id, h_organism_id, ant_type, ant_ref_name, ant_object_id, apc_cell_type, apc_tissue_type, apc_origin
    FROM mhc_elution
    WHERE mhc_elution_id IS NOT NULL AND
          reference_id IS NOT NULL AND
          curated_epitope_id IS NOT NULL AND
          as_char_value IS NOT NULL AND
          mhc_allele_restriction_id IS NOT NULL AND
          h_organism_id = 9606 AND
          ant_type = 'Epitope');
```

Количество строк

```{sql connection=con}
SELECT COUNT(*) FROM filtered_elution;
```

Нам необходима информация о МНС и о эпитопе. Подготовим по отдельности и объединим.

# Эпитопы

```{sql connection=con}
SELECT COUNT(*) FROM curated_epitope;
```

```{sql connection=con}
SELECT e_region_domain_flag, COUNT(e_region_domain_flag) FROM curated_epitope
GROUP BY e_region_domain_flag;
```

```{sql connection=con}
SELECT e_ev, COUNT(e_ev) FROM curated_epitope
GROUP BY e_ev;
```

Фильтруем, чтобы не было пустых идентификаторов, был "Exact Epitope" и "Exact match to reference information", "Internal Identifier-no external match available", "Author provided Identifier".

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW filtered_epitope_cur
AS (SELECT curated_epitope_id, e_name, e_object_id,e_region_domain_flag, e_ev, e_ref_start,e_ref_end
    FROM curated_epitope
    WHERE curated_epitope_id IS NOT NULL AND
          e_name IS NOT NULL AND
          e_object_id IS NOT NULL AND
          e_region_domain_flag = 'Exact Epitope' AND
          e_ev IN ('Exact match to reference information',
                   'Internal Identifier-no external match available',
                   'Author provided Identifier'));
```

```{sql connection=con}
SELECT COUNT(*) FROM filtered_epitope_cur;
```

# MHC

```{sql connection=con}
SELECT COUNT(*) FROM mhc_allele_restriction;
```

```{sql connection=con}
SELECT restriction_level, COUNT(restriction_level) FROM mhc_allele_restriction
GROUP BY restriction_level;
```

```{sql connection=con}
SELECT class, COUNT(class) FROM mhc_allele_restriction
GROUP BY class;
```

Нам нужны человеческие (NCBI Taxonomy ID 9606) МНС 1 класса.

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW filtered_mhc
AS (SELECT mhc_allele_restriction_id, restriction_level,displayed_restriction, organism_ncbi_tax_id,class, chain_i_name
    FROM mhc_allele_restriction
    WHERE mhc_allele_restriction_id IS NOT NULL AND
          restriction_level = 'complete molecule' AND
          organism_ncbi_tax_id = 9606 AND
          class = 'I');
```

```{sql connection=con}
SELECT COUNT(*) FROM filtered_mhc;
```

# BIND TOGETHER

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW epi_mhc_bind
AS (SELECT fb.mhc_bind_id, fe.curated_epitope_id, fe.e_name, fe.e_object_id,fe.e_region_domain_flag, fe.e_ev, fe.e_ref_start,fe.e_ref_end,fm.mhc_allele_restriction_id, fm.restriction_level,fm.displayed_restriction, fm.organism_ncbi_tax_id,fm.class, fm.chain_i_name
    FROM filtered_bind fb
    INNER JOIN filtered_mhc fm ON fm.mhc_allele_restriction_id = fb.mhc_allele_restriction_id
    INNER JOIN filtered_epitope_cur fe ON fe.curated_epitope_id = fb.curated_epitope_id);
```

```{sql connection=con}
SELECT COUNT(*) FROM epi_mhc_bind;
```

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW epi_mhc_elution
AS (SELECT fel.mhc_elution_id, fe.curated_epitope_id, fe.e_name, fe.e_object_id,fe.e_region_domain_flag, fe.e_ev, fe.e_ref_start,fe.e_ref_end,fm.mhc_allele_restriction_id, fm.restriction_level,fm.displayed_restriction, fm.organism_ncbi_tax_id,fm.class, fm.chain_i_name
    FROM filtered_elution fel
    INNER JOIN filtered_mhc fm ON fm.mhc_allele_restriction_id = fel.mhc_allele_restriction_id
    INNER JOIN filtered_epitope_cur fe ON fe.curated_epitope_id = fel.curated_epitope_id);
```

```{sql connection=con}
SELECT COUNT(*) FROM epi_mhc_elution;
```


Combine

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW elution_bind
AS (SELECT * FROM epi_mhc_bind
    UNION
    SELECT * FROM epi_mhc_elution);
```

```{sql connection=con}
SELECT COUNT(*) FROM elution_bind;
```

```{sql connection=con}
CREATE OR REPLACE ALGORITHM = TEMPTABLE
VIEW final_epi_mhc
AS (SELECT eb.e_name,eb.e_region_domain_flag,eb.e_ev, eb.e_ref_start, eb.e_ref_end,
eb.restriction_level, eb.displayed_restriction,eb.organism_ncbi_tax_id, eb.class,eb.chain_i_name, source_antigen_accession, source_organism_org_id,
description, linear_peptide_seq
FROM elution_bind eb
inner join epitope_object eo on eo.object_id = eb.e_object_id
inner join epitope e on eo.epitope_id = e.epitope_id
where source_antigen_accession is not null and 
      source_organism_org_id is not null and
      linear_peptide_seq is not null and linear_peptide_modification is null);
```

```{sql connection=con}
SELECT COUNT(*) FROM final_epi_mhc;
```

```{sql connection=con}
SELECT * FROM final_epi_mhc limit 10;
```





