project:
  type: book

book:
  title: "Предсказание антигенов по последовательностям белка"
  author: "Смирнов Антон Сергеевич"
  date: today
  date-format: "MMM D, YYYY"
  
  chapters:
    - abbreviatures.qmd
    - index.qmd
    - part: "Обзор литературы"
      chapters:
        - mhc.qmd
        - processing1.qmd
        - software.qmd
    - part: "Материалы и методы"
      chapters: 
        - concept.qmd
        - databases.qmd
        - modelling.qmd
    - part: "Результаты"
      chapters: 
        - proteasome.qmd
        - tap.qmd
        - pMHC.qmd
        - together.qmd
        - web-service.qmd
    - conclusion.qmd
    - discussion.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib
csl: gost-num-appear.csl
toc: true
toc-depth: 3
toc-title: "Оглавление"
fontsize: 14pt
linestretch: 1.5
geometry:
  - top=10mm
  - left=20mm
  - right=20mm
  - heightrounded
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 350px
  docx: 
    reference-doc: "diplom_template.docx"
  pdf:
    pdf-engine: xelatex
    header-includes: |
      \usepackage[utf8]{inputenc}
      \usepackage[american,russian]{babel}
      \usepackage{hyperref}  
      \usepackage{unicode-math}
mainfont: Arial
monofont: Arial
sansfont: Arial
editor: visual

