# Процессинг антигенов для MHC I

Процессинг антигенов для непосредственного МНС первого класса проходит в 6 стадий[@pishesha2022]:

1.  Получение антигена (фагоцитозом, пиноцитозом и прочими способами)
2.  Присоединение метки к белку в цитоплазме,
3.  Гидролиз меченого белка протеасомой на отдельные пептиды,
4.  Транспорт пептидов в ЭПР,
5.  Встраивание пептида в белок МНС первого класса,
6.  Транспорт комплекса на ЦПМ.

В качестве метки используется особый небольшой консервативный белок - убиквитин. Мечение осуществляется специальной убиквитин-протеосомальной системой (Ubiquitin-proteasomal system, UPS). Каскад реакций мечения описан в этой работе[@gong2016]. Сначала 1 молекула убиквитина ковалентно присоединяется к остатку цистеина убиквитин-активирующего фермента своим С-концевым остатком с затратой АТФ, затем он пересносится на убиквитин-конъюгирующий фермент. Следующим этапом убиквитин-конъюгирующий фермент формирует комплекс с убиквитинлигазой, с которой связан некоторый белковый субстрат. Убиквитинлигаза катализирует реакцию ковалентного связывания остатка лизина субстрата с С-концевым остатком глицина молекулы убиквитина. Дальнейший рост метки осуществялется убиквитинлигазой. Метка состоит из 4 молекул убиквитина, соедининенных между собой ковалентной связью между лизинами в 48 положении одной молекулы и С-концевым остатком глицина другой[@merfi2020].

Меченые белки поступают в особый белковый комплекс - протеасому. Существует множество типов протеосом, в зависимости от комбинации составляющих её частей[@tanaka2009]. Стандартная человеческая 26S протеасома состоит из 3 частей: активной зоны - 20S "бочонка", который состоит из 28 субъединиц, которые организованы в стопку из 4 колец: 2 $\beta$-кольца в центре и 2 $\alpha$-кольца по краям, - и 2 регуляторных 19S частей, решулирующие доступ внутрь каталитической области, распознающие меченый субстрат[@kloetzel2001]. Каталитическими являются лишь 1, 2 и 5 субъединицы $\beta$-колец. Разные субъединицы обладают разным типом химической активности, но нет определенных правил, позволяющих сказать по какому аминокислотному остатку точно произойдет расщепление в определенной последовательности. Характеристика каталитических субъединиц приведена в [@tbl-proteasome; @ferrington2012]. Существуют специальные каталитические субъединицы, которые экспрессируются при наличии IFN-$\gamma$, и они обладают несколько другим профилем активности, чем стандартные каталитические субъединицы. Кроме этого, есть специальная пятая субъединица, которая экспрессируется только в кортикальном слое тимуса эпителиальными клетками. По типу входящих в активную зону каталитических субъединиц выделяют конститутивные протеасомы, иммунопротеосомы и тимопротеосомы. Конститутивные протеасомы - те протеасомы, в состав которых входят только конститутивные субъединицы $\beta1$, $\beta2$ и $\beta5$. Иммунопротеосомами называют протеосому, в которой есть $\beta1i$, $\beta2i$ и $\beta5i$ субъединицы[@murata2018a]. Тимопротеосомой же называют специфичный для эпителиальных клеток кортикального слоя тимуса белковый комплекс, в состав которого входят $\beta1i$, $\beta2i$ и $\beta5t$ субъедиинцы[@murata2007]. Также существуют промежуточные формы иммунопротеосом, в которых произошла неполная замена конститутивных субъединиц на индуцированные.

| Субъединица | Общепринятое имя | Альтернативное имя                       | Ген    | Предпочтительная активность |
|---------------|---------------|---------------|---------------|---------------|
| Бета тип-6  | $\beta1$         | Y, Delta, LMP19, Pre3                    | PSMB6  | Каспазо-подобная            |
| Бета тип-9  | $\beta1i$        | Lmp2, RING12, MC7                        | PSMB9  | Химотрипсин-подобная        |
| Бета тип-7  | $\beta2$         | Z, MC14, Lmp9, Pup1                      | PSMB7  | Трипсин-подобная            |
| Бета тип-10 | $\beta2i$        | MECL-1, Lmp10                            | PSMB10 | Трипсин-подобная            |
| Бета тип-5  | $\beta5$         | X, epsilon, Lmp17, MB1, Pre2, Doa3, Prg1 | PSMB5  | Химотрипсин-подобная        |
| Бета тип-8  | $\beta5i$        | Lmp7, RING10, Y2, C13                    | PSMB8  | Химотрипсин-подобная        |
| Бета тип-11 | $\beta5t$        | Thymus-specific β5                       | PSMB11 | Химотрипсин-подобная        |

: Характеристика каталитических субъединиц протеосом. Суффикс i означает индуцированный, суффикс t - тимус-специфичный. Каспазо-подобная активность означает, что гидролиз пептидной связи предпочтителен после кислотных остатков аспартата и глутамат, трипсин-подобная активность - после основных остатков лизина и аргинина, химотрипсин-подобная - после гидрофобных остатков лейцина, триптофана, тирозина и фенилаланина. {#tbl-proteasome}

Анализ субстратной специфичности показывает, что конститутивная протеосома предпочитает выпускать пептиды с гидрофобными или основными остатками на С-конце, но это не означает, что не бывает других аминокислот на С-конце, к тому же у протеосом нет особых предпочтениям по другим позициям в итоговом пептиде, а наблюдаемые частоты аминокислотных остатков зависят от строения регуляторных и каталитических субъединиц используемой протеосомы[@harris]. Индуцированные субъединицы обладают отличающимся профилем каталитической активности: $\beta1i$ субъединица предпочитает гидрофобные остатки с разветвленной цепью, в отличие от $\beta1$, предпочитающей кислотные остатки, $\beta5i$ обладает ещё большим сродством к гидрофобным остаткам, чем $\beta5$, а профиль активности $\beta2$ и $\beta2i$ идентичен[@murata2018]. $\beta5t$ субъединица обладает пониженной химотрипсин-подобной активностью без влияния на каспазо-подобную и трипсин-подобную активности, что увеличивает долю пептидов с кислотным С-концевым остатком[@takahama2012]. Тимопротеосома участвует в положительной селекции CD8^+^-лимфоцитов[@kniepert2014]. Для положительной селекции лифоцитов важно, чтобы они распознали комплекс "свой пептид-МНС", поэтому тимопротеосома генерирует пептиды более похожие на собственные, в то время, как для иммунопротеосомы важно генерировать пептиды максимально непохожие на собственные для скорейшей реализации иммунного ответа.

С помощью UPS клетка избавляется как от поврежденных или ненужных белков, так и от дефективных рибосомальных продуктов (defective ribosomal products, DRiP). DRiP представляют из себя пептиды, транслированные с интронов на неправильно сплайсированных мРНК, транслированные с сдвигом рамки считывания и неправильно уложенные белки, меченные убиквитином для их быстрого разрушения протеосомой[@merfi2020]. Нарушения утилизации DRiP могут приводить к различным заболеваниям[@mediani2019]. DRiP также служат важным источником антигенных пептидов для презентирования на МНС I[@dolan2010].

В цитоплазме с продуктами гидролиза белков протеосомой могут произойти следующие события: утрата пост-трансляционных модификаций и пептидный сплайсинг, катализируемый протеосомой (proteosome-catalyzed peptide splicing, PCPS), дальнейший гидролиз с N-конца цитозольными протеазами. Например, гликопротеины теряют N-связанные гликаны[@suzuki2016]. Эта реакция конвертирует остаток аспарагина в остаток аспартата, что важно для распознания некоторых опухолевых антигенов[@vankasteren2014]. PCPS впервые наблюдали при анализе антигенов рака почки[@hanada2004]. Несмотря на то, что некоторые ученые сомневаются в существовании этого явления[@admon2021], оно наблюдается и изучается разными коллективами учёных[@vigneron2017; @mansurkhodzhaev2021; @mishto2019; @kato2022; @lichti2022], и большая часть иммунопептидома, который презентируется на HLA I класса, до 35% в некоторых клеточных линиях, может быть представлен сплайсированными пептидами[@liepe2016]. PCPS - процесс соедининия двух пептидов, продуцированных протеосомой. Она же и катилизирует реакцию сплайсинга. Механизм реакции заключается в атаке свободной аминогруппой одного пептида ацил-ферментного интермедиата[@vigneron2019]. Присоединение возможно в трех вариантах в зависимости от происхождения пептидов и порядка присоединения. Когда два пептида происходят из одного белка, говорят о цис-сплайсинге, если из двух разных белков, то о транс-сплайсинге. При цис-сплайсинге возможно два варианта. В первом случае пептиды присоединяются в том же порядке, как они идут в исходной последовательности, во втором случае же в обратном: пептид, который был ближе к С-концу исходного белка формирует N-конец сплайсированного пептида.

После выхода из протеосомы, пептиды достаточно длииные, чтобы не помещаться в пептидсвязывающую бороздку, могут дальше разрушаться с N-конца цитозольными протеазами. Есть убедительные доказательства, что после выхода из протеосомы, процессинг с С-конца не происходит в клетках[@rock2002; @craiu1997]. Показано, что участие в дальнейшем укорочении пептидов могут принимать участие пуромицин-чувствительная аминопептидаза, блеомуцингидролаза, анти-трипептидилпептидаза II [@stoltze2000; @rock2010]. От полного разрушения пептиды защищены шаперонами, например, кольцевым комплексом (TCP-1 ring complex, TRiC)[@kunisawa2003].

Далее пептиды подлежат транспорту в ЭР, где должно произойти их встраивание в МНС I. Их транслокацию обеспечивают специальные транспортеры, ассоциированные с антигенным процессингом (transporters associated with antigen processing, TAP). Это два белка, ТАР-1 и ТАР-2, из семейства АТФ-связывающих кассет (ATP-binding cassette, ABC), состоящие из N-концевого трансмембраного домена и С-концевого нуклеотид-связывающего домена[@daumke2001]. Гомодимеры этих белков не имеют функциональной активности[@urlinger1997]. Между трансмембранным доменом TAP-белков и белком тапасином есть солевой мостик, который важен для сборки пептид-загружающего комплекса (peptide-loading complex, PLC)[@blees2015]. Пептид связывается с транспортером, когда он в релаксированном состоянии, и иницирует в нем конформационные перестройки, в результате которых попадает в полость ЭР[@lehnert2017]. Гидролиз АТФ возвращает транспортер в исходное состояние[@abele2004]. Пептиды не покидают ЭР через TAP-транспортеры, так как их высокая концентрация в полости ЭР вызывает транс-ингибирование комплекса[@grossmann2014]. Только один пептид в один момент времени связывается с ТАР-комплексом[@herget2009]. Оптимальная длина пептида для переноса 8-16 аминокислот, хотя ТАР-1/2 способен переносить пептиды до 40 аминокислот[@vanendert1994; @gorbulev2001]. Важными для связывания с транспортером являются первые три N-концевые и одна С-концевая аминокислота[@herget2011]. Есть некоторые предпочтения по якорным остаткам у ТАР-транспортеров, а между ними участки могут сильно отличаться по длине и физико-химическим свойствам[@lehnert2017]. В позиции 1 и 2 N-конца предпочтительны положительно заряженные аминокислоты, в позиции 3 предпочтительны ароматические аминокислоты, в первых трех позициях не должно быть пролина, гиброфобные или основные аминокислоты на С-конце[@merfi2020; @androlewicz1994; @uebel1997].

После попадания пептида в ЭР он сразу поступает в PLC. PLC состоит из собраной молекулы HLA I, шаперона кальретикулина, ТАР-ассоциированного белка тапасина и тиоловой редуктазы ERp57[@blees2017]. Этот комплекс ответственен за присоединение эпитопа к молекуле HLA. Комплекс не загружает в молекулу HLA первый попавшийся пептид, а подбирает наиболее аффиный, удаляя низкоафииные. Этот процесс называется пептидным корректированием[@merfi2020]. Кроме этого, в полости ЭР есть специальные аминопептидазы, ассоциированные с антигенным процессингом (endoplasmatic reticulum aminopeptidase associated with antigen processing, ERAAP). Это два фермента, ERAP1 и ERAP2, которые представляют из цинковые протеазы с консервативным мотивом His-Glu-X-X-His-X18-Glu, которые также нарезают пептиды с N-конца[@serwold2002]. Экспрессия этих ферментов увеличивается под действием IFN-$\gamma$[@serwold2002]. Здоровые клетки с нокаутом этих генов продуцируют неиммунногенные пептиды или пептиды, которые вызывают гибель клетки из-за действия на них цитотоксических Т-лимфоцитов[@yewdell2012]. Пептиды, которым не удалось связаться с MHC удаляются из ЭР с помощью АТФ-зависимого транспортера Sec61[@osborne2005].

Следует иметь в виду, что процессинг антигена не совсем последовательный процесс. Например, получение эпитопа IYMDGTADSFSF из фермента тирозиназы проходит следующие стадии[@vigneron2017]:

1.  После синтеза белок попадает в ЭР, где происходит N-гликозилирование по специфичным аспарагиновым остаткам;

2.  После этого белок переносится в цитоплазму, но некоторые молекулы из них неправильно собираются, поэтому идут на утилизацию в UPS;

3.  У неправильно собранных белков произходит потеря N-связанных гликанов с конверсией аспарагина в аспартат;

4.  В протеосоме два пептида с такими конвертированными сайтами, IYMDGT и ADSFSF, соединияются (цис-прямой сплайсинг, катализированный протеосомой);

5.  Пептид IYMDGTADSFSF переносится в ЭР, загружается в молекулу MHC и полученный комплекс транспортируется на ЦПМ.
